### ISSUE TITLE
geocode error when query to Google returns multiple results 

### ISSUE THREAD

**Issue by JakeRuss** [dkahle/ggmap#24] opened 2013-11-12 23:19 UTC
Reproducible example:

geocode("Pelagonia, Macedonia", output = "more")

Returns the message
Information from URL : http://maps.googleapis.com/maps/api/geocode/json?address=Pelagonia,+Macedonia&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
Error in data.frame(long_name = "Pelagonia", short_name = "Pelagonia",  : 
  arguments imply differing number of rows: 1, 0

**Comment by rschoenbeck** [comment] 2015-02-01 20:18
I'm getting the same issue when using output = "more". Here's a new reproducible example:

geocode("Zurite, Peru", output = "more")

This example works fine when I use lat/lon or "all," so I think I'll go with output = "all" for now.

Err msg:
Error in data.frame(long_name = "Zurite", short_name = "Zurite", types = list(),  : 
  arguments imply differing number of rows: 1, 0

**Comment by jcbaker1** [comment] 2016-05-16 13:24
@andraderdz 
I'm trying to do something like this now. Did you ever manage to figure it out?
Thanks!

**Comment by scottmmjackson** [comment] 2018-02-09 23:40
I can't reproduce these. If you can, please use a [reprex](https://github.com/tidyverse/reprex) set to the github venue and post it. Closing for now.

**Closed by scottmmjackson** 2018-02-09 23:40 UTC
