### ISSUE TITLE
Reflect that Stamen tiles are now hosted by Stadia Maps

### ISSUE THREAD

**Issue by ianthetechie** [dkahle/ggmap#350] opened 2023-08-28 05:25 UTC
See http://maps.stamen.com/stadia-partnership/ and https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/.

This will probably be a semver breaking change regardless of any reorganization (since an API key will be required in the future). Additionally, the approach taken by [Leaflet Providers](https://github.com/leaflet-extras/leaflet-providers/pull/520), [OpenLayers](https://github.com/openlayers/openlayers/issues/14963), etc. has been to change the source name while we're making breaking changes anyways.

I'll try to work up a PR myself and let you know if I get stuck; my R is a bit rusty ;)

**Comment by ianthetechie** [comment] 2023-09-20 12:29
Quick bump on this for the project maintainers. We are still planning to start brownouts toward the end of September to let people know to switch over. It would be great to get ggmap updated ASAP since I assume many users and platforms have a longer update cycle.

**Comment by Eric-Arellano** [comment] 2023-09-20 15:39
> It would be great to get ggmap updated ASAP since I assume many users and platforms have a longer update cycle.

Indeed. We're using Shiny for https://parkingreform.org/mandates-map/ and are worried we won't be able to fix this in time. We've been migrating from Shiny to using Leaflet directly, which will avoid the problem. But we'd be in trouble if we hadn't already started the migration before this change to Stamen was announced.

**Comment by ianthetechie** [comment] 2023-10-03 18:07
As a note to anyone finding this via a Google search wondering why their maps include warning tiles from Stamen, we have started serving brownout tiles infrequently in order to let developers know they have less than a month to upgrade. Hopefully the open PR can get merged soon.

**Comment by ferrancarril** [comment] 2023-10-06 09:28
Hi! We're currently using `get_stamenmap` to include a heat map in some reports made with R. Since October 4th when generating our reports the pipeline sometimes fails on this step.

<img width="627" alt="image" src="https://github.com/dkahle/ggmap/assets/96413644/39848424-e8ff-49d9-bb51-993d436a5155">

Is this related to brownout tiles? Is there any workaround for that until the PR is merged? This is some legacy project we're maintaining and I'm not an expert in R.
Thank you.

**Comment by ianthetechie** [comment] 2023-10-06 10:04
Hello @ferrancarril. I think this is probably related, but I unfortunately don't know the internals of the ggmap library that well.

We just updated our guide a few hours ago with details on how to install our patched version until the PR is merged. Let me know if you have any questions!

https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/#ggmap

**Comment by ZacWarham** [comment] 2023-10-08 22:28
> Hello @ferrancarril. I think this is probably related, but I unfortunately don't know the internals of the ggmap library that well.
> 
> We just updated our guide a few hours ago with details on how to install our patched version until the PR is merged. Let me know if you have any questions!
> 
> https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/#ggmap

I can confirm that @ferrancarril is related to the brownout of stamen_map and I have successfully been able to get it working using a similar steps to what you provided above

The same problem is shown in https://github.com/dkahle/ggmap/issues/353

**Closed** 2023-11-01 16:49 UTC
