### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle) :    schannel: failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by DXH89478273ok** [dkahle/ggmap#237] opened 2018-10-20 03:37 UTC
## Reproducible Example

Dear dkahle,

Recent days, I am tick to the probelm from the funtion of get_map() of ggmap. I installed the ggmap package from the way described by you, but I still get the error presented below. Hope you can help, many thanks.

Example:

```r
lat <- c(14, 65)                
lon <- c(76, 135)
register_google(key = "my_API_key")

base <- get_map(location = c(lon = mean(lon), lat = mean(lat)), zoom = 10, maptype = "terrain-background", source = "stamen")

}, si = TRUE)
```
Source : https://maps.googleapis.com/maps/api/staticmap?center=22.5,83.5&zoom=10&size=640x640&scale=2&maptype=terrain&key=xxx://maps.google.co.jp/maps/api/js?sensor=false
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by wpwang90** [comment] 2018-11-03 07:00
I have the same problem.  So sad.

**Comment by dkahle** [comment] 2018-11-03 14:47
__ggmap__ connects with Google Maps over the encrypted [https](https://en.wikipedia.org/wiki/HTTPS) protocol, which operates over [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security) formerly called SSL, for added security. In that sense, since __ggmap__ does not manage the connections, this doesn't appear to be a __ggmap__ issue. (The error is coming from __curl__'s `curl()`.) 

That being said, the URL you provided doesn't look well-formed, as it has the `.co.jp` extension, and then uses `js`. Maybe Google doesn't like where you're querying from?

**Comment by wpwang90** [comment] 2018-11-04 04:55
> **ggmap** connects with Google Maps over the encrypted [https](https://en.wikipedia.org/wiki/HTTPS) protocol, which operates over [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security) formerly called SSL, for added security. In that sense, since **ggmap** does not manage the connections, this doesn't appear to be a **ggmap** issue. (The error is coming from **curl**'s `curl()`.)
> 
> That being said, the URL you provided doesn't look well-formed, as it has the `.co.jp` extension, and then uses `js`. Maybe Google doesn't like where you're querying from?
Thank you so much for your reply. I just run the demo code and got this error. Like that:

hdf <- get_map("houston, texas")

and 

map <- get_map()

All these codes return 
Error in curl::curl_fetch_memory(url, handle = handle) :
schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by dkahle** [comment] 2018-11-06 15:07
As I mentioned above, this does not appear to be a __ggmap__ problem, so this is probably not the best forum for these kinds of questions. It is not clear to me what the problem is. I would try re-installing the underlying packages (__curl__, the [curl library](https://curl.haxx.se), __httr__, etc.), then try to problem solve any persistent connection issue.

__ggmap__ queries webpages using those technologies via a valid, well-formed URL. The only place where this could be a __ggmap__ problem is if __ggmap__ is not forming that URL properly, which I'm open to (there may be a bug), but I think at this stage it's much more likely that either 1) you haven't installed the right version of __ggmap__, in which case you need to go to read the __ggmap__ GitHub readme (just go to the main page on this same site) or 2) your lower-level stuff isn't working properly. I'm going to close this issue now, if it persists, please get back and I'll reopen.

**Closed by dkahle** 2018-11-06 15:07 UTC

**Comment by stonegz** [comment] 2018-11-06 20:12
For proxy users, if you have set up your google api key, you might try
1. set urlonly = TRUE, and check the url is working;
get_googlemap("waco texas", urlonly = TRUE)
[1] "https://maps.googleapis.com/maps/api/staticmap?center=waco%20texas&zoom=10&size=640x640&scale=2&maptype=terrain&key=XXX"

2.  you might need to set the proxy as following for an example,
httr::set_config(httr::use_proxy(url = "http://127.0.0.1", port = 1080), override = TRUE)

**Comment by EraProphet** [comment] 2019-09-19 09:09
> ## Reproducible Example
> Dear dkahle,
> 
> Recent days, I am tick to the probelm from the funtion of get_map() of ggmap. I installed the ggmap package from the way described by you, but I still get the error presented below. Hope you can help, many thanks.
> 
> Example:
> 
> ```r
> lat <- c(14, 65)                
> lon <- c(76, 135)
> register_google(key = "my_API_key")
> 
> base <- get_map(location = c(lon = mean(lon), lat = mean(lat)), zoom = 10, maptype = "terrain-background", source = "stamen")
> 
> }, si = TRUE)
> ```
> 
> Source : https://maps.googleapis.com/maps/api/staticmap?center=22.5,83.5&zoom=10&size=640x640&scale=2&maptype=terrain&key=xxx://maps.google.co.jp/maps/api/js?sensor=false
> Error in curl::curl_fetch_memory(url, handle = handle) :
> schannel: failed to receive handshake, SSL/TLS connection failed

I have also encountered the same problem as you. If you had solved this problem, I need your help! thank you

**Comment by jiangfenglyu** [comment] 2021-06-23 11:25
> For proxy users, if you have set up your google api key, you might try
> 
> 1. set urlonly = TRUE, and check the url is working;
>    get_googlemap("waco texas", urlonly = TRUE)
>    [1] "https://maps.googleapis.com/maps/api/staticmap?center=waco%20texas&zoom=10&size=640x640&scale=2&maptype=terrain&key=XXX"
> 2. you might need to set the proxy as following for an example,
>    httr::set_config(httr::use_proxy(url = "http://127.0.0.1", port = 1080), override = TRUE)

this one worked for me, suggest you all try this. thanks @stonegz

**Comment by Fredo-XVII** [comment] 2023-11-16 19:52
@stonegz Thank you!!! Thank you!!! I can't believe that work so easily.  I have been looking for this solution for nearly 2 years. Of course I used the proxy url and port specific to my firm.
