### ISSUE TITLE
mutate_geocode() returns "Error: is.character(location) is not TRUE" while location is a character

### ISSUE THREAD

**Issue by taraskaduk** [dkahle/ggmap#175] opened 2017-09-30 15:10 UTC
Hi there.
Here is what I run into.

```
library(tidyverse)
library(ggmap)

df1 <- tibble(city = c('London',
                       'Brussels',
                       'New York'), 
                status = 'status1')

df2 <- tibble(city = c('Atlanta',
                        'Orlando',
                        'Paris'), 
               status = 'status2')

cities <- bind_rows(df1, df2)

mutate_geocode(cities, city)
```

```
mutate_geocode(cities, city)
Error: is.character(location) is not TRUE
In addition: Warning message:
drop ignored 
```

Just so that I'm not crazy...
```
> class(cities$city)
[1] "character"
> is.character(cities$city)
[1] TRUE
```

The only way to make it work is to resort to base R data.frame() and explicitly state `stringsAsFactors = FALSE ` (which `tibble()` and `data_frame()` do by default)

**Comment by mvkorpel** [comment] 2017-10-12 11:05
Is this a duplicate of #106 ?

**Comment by taraskaduk** [comment] 2017-10-12 18:19
I apologize. It is. I didn't see this issue

**Closed** 2018-02-09 22:26 UTC

**Comment by vijayaraghavan-radhika** [comment] 2022-11-12 11:21
It doesnt work still even with base R data.frame() and stringsAsFactors = FALSE!! how to resolve this error?
