### ISSUE TITLE
Hi @andreapierucci –

### ISSUE THREAD

**Issue by wpwang90** [dkahle/ggmap#247] opened 2018-11-03 07:09 UTC
Would do mind giving me some help?
When I use get_map after I register_google by my key. There is an error: 

Source: https://maps.googleapis.com/maps/api/geocode/json?address=the%20hollyood%20bowl&key=xxx-fwNH7vld-gv8SNI
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by dkahle** [comment] 2018-11-03 14:41
Duplicate of #237.

**Closed by dkahle** 2018-11-03 14:41 UTC
